<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */



$packageNameLower = 'oauth2x'; /* No spaces, no dashes */

$components = array(
    /* These are used to define the package and set values for placeholders */
    'packageName' => 'OAuth2X',  /* No spaces, no dashes */
    'packageNameLower' => $packageNameLower,
    'packageDescription' => '',
    'version' => '0.2.5',
    'release' => '',
    'author' => 'Grey Sky Media',
    'email' => 'support@greyskymedia.com',
    'authorUrl' => 'https://greyskymedia.com',
    'authorSiteName' => "Grey Sky Media",
    'packageDocumentationUrl' => 'https://github.com/Polumathes/OAuth2X',
    'copyright' => '2019',

    /* no need to edit this except to change format */
    'createdon' => strftime('%m-%d-%Y'),

    'gitHubUsername' => '',
    'gitHubRepository' => '',

    /* two-letter code of your primary language */
    'primaryLanguage' => 'en',

    /* Set directory and file permissions for project directories */
    'dirPermission' => 0755,  /* No quotes!! */
    'filePermission' => 0644, /* No quotes!! */

    /* Define source and target directories */

    /* path to MyComponent source files */
    'mycomponentRoot' => $this->modx->getOption('mc.root', null,
        MODX_CORE_PATH . 'components/mycomponent/'),

    /* path to new project root */
    'targetRoot' => MODX_ASSETS_PATH . 'mycomponents/' . $packageNameLower . '/',


    /* *********************** NEW SYSTEM SETTINGS ************************ */

    /* If your extra needs new System Settings, set their field values here.
     * You can also create or edit them in the Manager (System -> System Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra */

    'newSystemSettings' => array(
       'oauth2x_system_setting1' => array( // key
            'key' => 'oauth2server.enabled',
            'name' => 'OAuth2Server Enabled',
            'description' => 'Enable OAuth2 services',
            'namespace' => 'oauth2server',
            'xtype' => 'combo-boolean',
            'value' => '1',
            'area' => '',
        ),
    ),

    /* ************************ NEW SYSTEM EVENTS ************************* */

    /* Array of your new System Events (not default
     * MODX System Events). Listed here so they can be created during
     * install and removed during uninstall.
     *
     * Warning: Do *not* list regular MODX System Events here !!! */

    'newSystemEvents' => array(
       /* 'OnMyEvent1' => array(
            'name' => 'OnMyEvent1',
        ),
        'OnMyEvent2' => array(
            'name' => 'OnMyEvent2',
            'groupname' => 'OAuth2X',
            'service' => 1,
        ),*/
    ),

    /* ************************ NAMESPACE(S) ************************* */
    /* (optional) Typically, there's only one namespace which is set
     * to the $packageNameLower value. Paths should end in a slash
    */

    'namespaces' => array(
        'oauth2server' => array(
            'name' => 'oauth2server',
            'path' => '{core_path}components/oauth2x/',
            'assets_path' => '{assets_path}components/oauth2x/',
        ),
        'oauth2x' => array(
            'name' => 'oauth2x',
            'path' => '{core_path}components/oauth2x/',
            'assets_path' => '{assets_path}components/oauth2x/',
        ),
    ),

    /* ************************ CONTEXT(S) ************************* */
    /* (optional) List any contexts other than the 'web' context here
    */

    'contexts' => array(
        /*'oauth2x' => array(
            'key' => 'oauth2x',
            'description' => 'oauth2x context',
            'rank' => 2,
        )*/
    ),

    /* *********************** CONTEXT SETTINGS ************************ */

    /* If your extra needs Context Settings, set their field values here.
     * You can also create or edit them in the Manager (Edit Context -> Context Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra.
     * The context_key should be the name of an actual context.
     * */

    'contextSettings' => array(
        /*'oauth2x_context_setting1' => array(
            'context_key' => 'oauth2x',
            'key' => 'oauth2x_context_setting1',
            'name' => 'OAuth2X Setting One',
            'description' => 'Description for setting one',
            'namespace' => 'oauth2x',
            'xtype' => 'textfield',
            'value' => 'value1',
            'area' => 'oauth2x',
        ),
        'oauth2x_context_setting2' => array(
            'context_key' => 'oauth2x',
            'key' => 'oauth2x_context_setting2',
            'name' => 'OAuth2X Setting Two',
            'description' => 'Description for setting two',
            'namespace' => 'oauth2x',
            'xtype' => 'combo-boolean',
            'value' => true,
            'area' => 'oauth2x',
        ),*/
    ),

    /* ************************* CATEGORIES *************************** */
    /* (optional) List of categories. This is only necessary if you
     * need to categories other than the one named for packageName
     * or want to nest categories.
    */

    'categories' => array(
        'OAuth2Server' => array(
            'category' => 'OAuth2Server',
            'parent' => '',  /* top level category */
        ),
        /*'category2' => array(
            'category' => 'Category2',
            'parent' => 'OAuth2X', // nested under OAuth2X 
        )*/
    ),

    /* *************************** MENUS ****************************** */

    /* If your extra needs Menus, you can create them here
     * or create them in the Manager, and export them with exportObjects.
     * Be sure to set their namespace to the lowercase package name
     * of your extra.
     *
     * Every menu should have exactly one action */

    'menus' => array(
        'OAuth2Server' => array(
            'text' => 'oauth2server.menu.manage',
            'parent' => 'components',
            'description' => 'oauth2server.menu.manage_desc',
            'icon' => '',
            'menuindex' => 0,
            'params' => '',
            'handler' => '',
            'permissions' => '',

            'action' => 'manage',
        ),
    ),


    /* ************************* ELEMENTS **************************** */

    /* Array containing elements for your extra. 'category' is required
       for each element, all other fields are optional.
       Property Sets (if any) must come first!

       The standard file names are in this form:
           SnippetName.snippet.php
           PluginName.plugin.php
           ChunkName.chunk.html
           TemplateName.template.html

       If your file names are not standard, add this field:
          'filename' => 'actualFileName',
    */


    'elements' => array(

        'propertySets' => array( // all three fields are required 
            'VerifyOAuth2Context' => array(
                'name' => 'VerifyOAuth2Context',
                'description' => 'Properties for VerifyOAuth2Context Plugin',
                'category' => 'OAuth2Server',
            ),
            /*'PropertySet2' => array(
                'name' => 'PropertySet2',
                'description' => 'Description for PropertySet2',
                'category' => 'OAuth2X',
            ),*/
        ),

        'snippets' => array(
            'verifyOAuth2' => array(
                'category' => 'OAuth2Server',
                'description' => '',
                'static' => true,
            ),
            'authorizeOAuth2' => array(
                'category' => 'OAuth2Server',
                'description' => '',
                'static' => true,
            ),
            'grantOAuth2Tokens' => array(
                'category' => 'OAuth2Server',
                'description' => '',
                'static' => true,
            ),
        ),
        'plugins' => array(
            'VerifyOAuth2Context' => array( //oauth2x with static, events, and property sets
                'category' => 'OAuth2Server',
                'description' => '',
                'static' => true,
                'propertySets' => array( //all property sets to be connected to element
                    'VerifyOAuth2Context',
                ),
                'events' => array(
                    // minimal oauth2x - no fields 
                    'OnUserFormSave' => array(),
                    // oauth2x with fields set 
                    'OnWebPageInit' => array(
                        'priority' => '0', // priority of the event -- 0 is highest priority
                        'group' => 'plugins',  // should generally be set to 'plugins' 
                        'propertySet' => 'VerifyOAuth2Context', // property set to be used in this pluginEvent
                    ),
                ),
            ),
        ),
        'chunks' => array(
            'oauth2server_auth_tpl' => array(
                'category' => 'OAuth2Server',
            ),
           /* 'Chunk2' => array(
                'description' => 'Description for Chunk two',
                'category' => 'OAuth2X',
                'static' => false,
                'propertySets' => array(
                    'PropertySet2',
                ),
            ),*/
        ),
        'templates' => array(
           /* 'Template1' => array(
                'category' => 'OAuth2X',
            ),
            'Template2' => array(
                'category' => 'OAuth2X',
                'description' => 'Description for Template two',
                'static' => false,
                'propertySets' => array(
                    'PropertySet2',
                ),
            ),*/
        ),
        'templateVars' => array(
            /*'Tv1' => array(
                'category' => 'OAuth2X',
                'description' => 'Description for TV one',
                'caption' => 'TV One',
                'default_text' => 'Tv1 Default Text',
                'propertySets' => array(
                    'PropertySet1',
                    'PropertySet2',
                ),
                'templates' => array(
                    'default' => 1,
                    'Template1' => 4,
                    'Template2' => 4,


                ),
            ),
            'Tv2' => array( //oauth2x with templates, default, and static specified 
                'category' => 'OAuth2X',
                'description' => 'Description for TV two',
                'caption' => 'TV Two',
                'static' => false,
                'default_text' => '@INHERIT',
                'templates' => array(
                    'default' => 3, //second value is rank -- for ordering TVs when editing resource 
                    'Template1' => 4,
                    'Template2' => 1,
                ),
            ),*/
        ),
    ),
    /* (optional) will make all element objects static - 'static' field above will be ignored */
    'allStatic' => false,


    /* ************************* RESOURCES ****************************
     Important: This list only affects Bootstrap. There is another
     list of resources below that controls ExportObjects.
     * ************************************************************** */
    /* Array of Resource pagetitles for your Extra; All other fields optional.
       You can set any resource field here */
    'resources' => array(
        'Resource1' => array( //minimal oauth2x 
            'pagetitle' => 'OAuth2 Token Controller',
            'alias' => 'tokens',
            "template" => 0,
            "content_type" => 7,
            "published" => 1,
            "hidemenu" => 1,
            "cacheable" => 0,
            "richtext" => 0,
        ),
        'Resource2' => array( //minimal oauth2x
            'pagetitle' => 'OAuth2 Authorization',
            'alias' => 'auth',
            "template" => 0,
            "published" => 1,
            "hidemenu" => 1,
            "cacheable" => 0,
            "richtext" => 0,
        ),
        'Resource3' => array( //minimal oauth2x
            'pagetitle' => 'OAuth2 Verification Example',
            'alias' => 'verify',
            "template" => 0,
            "content_type" => 7,
            "published" => 1,
            "hidemenu" => 1,
            "cacheable" => 0,
            "richtext" => 0,
        ),
    ),


    /* Array of languages for which you will have language files,
     *  and comma-separated list of topics
     *  ('.inc.php' will be added as a suffix). */
    'languages' => array(
        'en' => array(
            'default',
        ),
    ),
    /* ********************************************* */
    /* Define optional directories to create under assets.
     * Add your own as needed.
     * Set to true to create directory.
     * Set to hasAssets = false to skip.
     * Empty js and/or css files will be created.
     */
    'hasAssets' => false,

    'assetsDirs' => array(
        /* If true, a default (empty) CSS file will be created */
        'css' => false,

        /* If true, a default (empty) JS file will be created */
        'js' => false,

        'images' => false,
        'audio' => false,
        'video' => false,
        'themes' => false,
    ),
    /* minify any JS files */
    'minifyJS' => false,
    /* Create a single JS file from all JS files */
    'createJSMinAll' => false,
    /* if this is false, regular jsmin will be used.
       JSMinPlus is slower but more reliable */
    'useJSMinPlus' => false,

    /* These will automatically go under assets/components/yourcomponent/js/
       Format: directory:filename
       (no trailing slash on directory)
       if 'createCmpFiles is true, these will be ignored.
    */
    'jsFiles' => array(
        //'oauth2x.js',
    ),

    /* Desired CSS files */
    'cssFiles' => array(
        //'oauth2x.css',
    ),

    /* ********************************************* */
    /* Define basic directories and files to be created in project*/

    'docs' => array(
        'readme.txt',
        'license.txt',
        'changelog.txt',
        'tutorial.html'
    ),

    /* (optional) Description file for GitHub project home page */
    'readme.md' => true,
    /* assume every package has a core directory */
    'hasCore' => true,

    /* ********************************************* */
    /* (optional) Array of extra script resolver(s) to be run
     * during install. Note that resolvers to connect plugins to events,
     * property sets to elements, resources to templates, and TVs to
     * templates will be created automatically -- *don't* list those here!
     *
     * 'default' creates a default resolver named after the package.
     * (other resolvers may be created above for TVs and plugins).
     * Suffix 'resolver.php' will be added automatically */
    'resolvers' => array(
        'default'
    ),

    /* (optional) Validators can abort the install after checking
     * conditions. Array of validator names (no
     * prefix of suffix) or '' 'default' creates a default resolver
     *  named after the package suffix 'validator.php' will be added */

    'validators' => array(
        'default'
    ),

    /* (optional) install.options is needed if you will interact
     * with user during the install.
     * See the user.input.php file for more information.
     * Set this to 'install.options' or ''
     * The file will be created as _build/install.options/user.input.php
     * Don't change the filename or directory name. */
    'install.options' => 'install.options',


    /* Suffixes to use for resource and element code files (not implemented)  */
    'suffixes' => array(
        'modPlugin' => '.php',
        'modSnippet' => '.php',
        'modChunk' => '.html',
        'modTemplate' => '.html',
        'modResource' => '.html',
    ),


    /* ********************************************* */
    /* (optional) Only necessary if you will have class files.
     *
     * Array of class files to be created.
     *
     * Format is:
     *
     * 'ClassName' => 'directory:filename',
     *
     * or
     *
     *  'ClassName' => 'filename',
     *
     * ('.class.php' will be appended automatically)
     *
     *  Class file will be created as:
     * yourcomponent/core/components/yourcomponent/model/[directory/]{filename}.class.php
     * Note: If a CMP is being created, classes containing the
     * project name will be ignored here.
     *
     * Set to array() if there are no classes. */
    'classes' => array(
        'OAuth2ServerClients' => 'oauth2server:oauth2serverclients',
        'OAuth2ServerAccessTokens' => 'oauth2server:oauth2serveraccesstokens',
        'OAuth2ServerAuthorizationCodes' => 'oauth2server:oauth2serverauthorizationcodes',
        'OAuth2ServerRefreshTokens' => 'oauth2server:oauth2serverrefreshtokens',
        'OAuth2ServerScopes' => 'oauth2server:oauth2serverscopes',
        'OAuth2ServerJwt' => 'oauth2server:oauth2serverjwt',
    ),

    /* ************************************
     *  These values are for CMPs.
     *  Set any of these to an empty array if you don't need them.
     *  **********************************/

    /* If this is false, the rest of this section will be ignored */

    'createCmpFiles' => true,

    /* IMPORTANT: The array values in the rest of
       this section should be all lowercase */

    /* This is the main action file for your component.
       It will automatically go in core/component/yourcomponent/
    */

    'actionFile' => 'index.class.php',

    /* CSS file for CMP */

    'cssFile' => 'mgr.css',

    /* These will automatically go to core/components/yourcomponent/processors/
       format directory:filename
       '.class.php' will be appended to the filename

       Built-in processor classes include getlist, create, update, duplicate,
       import, and export. */

    'processors' => array(
//        'mgr/snippet:getlist',
//        'mgr/snippet:changecategory',
//        'mgr/snippet:remove',
//
//        'mgr/chunk:getlist',
//        'mgr/chunk:changecategory',
//        'mgr/chunk:remove',
    ),

    /* These will automatically go to core/components/yourcomponent/controllers[/directory]/filename
       Format: directory:filename */

    'controllers' => array(
        ':manage.class.php',
    ),

    /* These will automatically go in assets/components/yourcomponent/ */

    'connectors' => array(
        'connector.php'

    ),
    /* These will automatically go to assets/components/yourcomponent/js[/directory]/filename
       Format: directory:filename */

    'cmpJsFiles' => array(
//        ':oauth2x.class.js',
//        'sections:home.js',
//        'widgets:home.panel.js',
//        'widgets:snippet.grid.js',
//        'widgets:chunk.grid.js',
    ),

    /* These go to core/components/componentName/templates/
     * The format is:
     *    filename:content
     * content is optional
     */

    'cmpTemplates' => array (
         '',
    ),


    /* *******************************************
     * These settings control exportObjects.php  *
     ******************************************* */
    /* ExportObjects will update existing files. If you set dryRun
       to '1', ExportObjects will report what it would have done
       without changing anything. Note: On some platforms,
       dryRun is *very* slow  */

    'dryRun' => '0',

    /* Array of elements to export. All elements set below will be handled.
     *
     * To export resources, be sure to list pagetitles and/or IDs of parents
     * of desired resources
    */
    'process' => array(
        'contexts',
        'snippets',
        'plugins',
        'templateVars',
        'templates',
        'chunks',
        'resources',
        'propertySets',
        'systemSettings',
        'contextSettings',
        'systemEvents',
        'menus'
    ),
    /*  Array  of resources to process. You can specify specific resources
        or parent (container) resources, or both.

        They can be specified by pagetitle or ID, but you must use the same method
        for all settings and specify it here. Important: use IDs if you have
        duplicate pagetitles */
    'getResourcesById' => false,

    'exportResources' => array(
        //'Resource1',
        //'Resource2',
    ),
    /* Array of resource parent IDs to get children of. */
    'parents' => array(),
    /* Also export the listed parent resources
      (set to false to include just the children) */
    'includeParents' => false,


    /* ******************** LEXICON HELPER SETTINGS ***************** */
    /* These settings are used by LexiconHelper */
    'rewriteCodeFiles' => false,  /* remove ~~descriptions */
    'rewriteLexiconFiles' => true, /* automatically add missing strings to lexicon files */
    /* ******************************************* */

    /* Array of aliases used in code for the properties array.
     * Used by the checkproperties utility to check properties in code against
     * the properties in your properties transport files.
     * if you use something else, add it here (OK to remove ones you never use.
     * Search also checks with '$this->' prefix -- no need to add it here. */
    'scriptPropertiesAliases' => array(
        'props',
        'sp',
        'config',
        'scriptProperties'
    ),
);

return $components;